# -*- coding: utf-8 -*-
"""TASK1 HPC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VqHdajzWWwLHRPB0Yn_6wGRRboSbDq1c
"""

!apt-get update
!apt-get install -y nvidia-cuda-toolkit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile vector_add.cu
# #include <stdio.h>
# #include <chrono>
# #include <cuda.h>
# using namespace std;
# #define N 1000000
# // GPU kernel
# __global__ void vectorAddGPU(int *a, int *b, int *c)
# {
#     int tid = blockIdx.x * blockDim.x + threadIdx.x;
# 
#     if(tid < N)
#         c[tid] = a[tid] + b[tid];
# }
# // CPU function
# void vectorAddCPU(int *a, int *b, int *c)
# {
#     for(int i = 0; i < N; i++)
#         c[i] = a[i] + b[i];
# }
# int main()
# {
#     int *h_a, *h_b, *h_c;
#     int *d_a, *d_b, *d_c;
# 
#     size_t size = N * sizeof(int);
# 
#     h_a = (int*)malloc(size);
#     h_b = (int*)malloc(size);
#     h_c = (int*)malloc(size);
# 
#     for(int i=0;i<N;i++)
#     {
#         h_a[i] = i;
#         h_b[i] = i*2;
#     }
#     // CPU time
#     auto start_cpu = chrono::high_resolution_clock::now();
#     vectorAddCPU(h_a,h_b,h_c);
#     auto end_cpu = chrono::high_resolution_clock::now();
#     chrono::duration<float,milli> cpu_time = end_cpu-start_cpu;
#     printf("CPU Time: %f ms\n", cpu_time.count());
#     cudaMalloc(&d_a,size);
#     cudaMalloc(&d_b,size);
#     cudaMalloc(&d_c,size);
#     cudaMemcpy(d_a,h_a,size,cudaMemcpyHostToDevice);
#     cudaMemcpy(d_b,h_b,size,cudaMemcpyHostToDevice);
#     int threads = 256;
#     int blocks = (N+threads-1)/threads;
#     // GPU time
#     auto start_gpu = chrono::high_resolution_clock::now();
#     vectorAddGPU<<<blocks,threads>>>(d_a,d_b,d_c);
#     cudaDeviceSynchronize();
#     auto end_gpu = chrono::high_resolution_clock::now();
#     chrono::duration<float,milli> gpu_time = end_gpu-start_gpu;
#     printf("GPU Time: %f ms\n", gpu_time.count());
#     cudaFree(d_a);
#     cudaFree(d_b);
#     cudaFree(d_c);
#     return 0;
# }

!nvcc vector_add.cu -o vector_add

!./vector_add

import matplotlib.pyplot as plt
cpu_time = 28
gpu_time = 3
labels = ["CPU","GPU"]
times = [cpu_time,gpu_time]
plt.bar(labels,times)
plt.ylabel("Execution Time (ms)")
plt.title("CPU vs GPU Vector Addition Performance")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
P = np.linspace(0,1,10)
S = 10
speedup = 1 / ((1-P) + (P/S))
plt.plot(P,speedup,marker='o')
plt.xlabel("Parallel Portion")
plt.ylabel("Speedup")
plt.title("Amdahl's Law")
plt.grid(True)
plt.show()

