# -*- coding: utf-8 -*-
"""TASK2 HPC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kv3QEWGe_N_nUetIUVsv2kx6ngsJvwjO
"""

!nvidia-smi

!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# %%writefile matmul.cu
# #include <iostream>
# using namespace std;
# 
# #define N 16
# 
# __global__ void matrixMul(int *A, int *B, int *C)
# {
#     int row = blockIdx.y * blockDim.y + threadIdx.y;
#     int col = blockIdx.x * blockDim.x + threadIdx.x;
# 
#     if(row < N && col < N)
#     {
#         int sum = 0;
# 
#         for(int k=0;k<N;k++)
#         {
#             sum += A[row*N + k] * B[k*N + col];
#         }
# 
#         C[row*N + col] = sum;
#     }
# }
# 
# int main()
# {
#     int size = N*N*sizeof(int);
# 
#     int *A = new int[N*N];
#     int *B = new int[N*N];
#     int *C = new int[N*N];
# 
#     for(int i=0;i<N*N;i++)
#     {
#         A[i] = 1;
#         B[i] = 2;
#     }
# 
#     int *d_A,*d_B,*d_C;
# 
#     cudaMalloc((void**)&d_A,size);
#     cudaMalloc((void**)&d_B,size);
#     cudaMalloc((void**)&d_C,size);
# 
#     cudaMemcpy(d_A,A,size,cudaMemcpyHostToDevice);
#     cudaMemcpy(d_B,B,size,cudaMemcpyHostToDevice);
# 
#     dim3 threads(16,16);
#     dim3 blocks(1,1);
# 
#     matrixMul<<<blocks,threads>>>(d_A,d_B,d_C);
# 
#     cudaDeviceSynchronize();
# 
#     cudaMemcpy(C,d_C,size,cudaMemcpyDeviceToHost);
# 
#     cout<<"Result Matrix:\n";
# 
#     for(int i=0;i<N;i++)
#     {
#         for(int j=0;j<N;j++)
#         {
#             cout<<C[i*N+j]<<" ";
#         }
#         cout<<endl;
#     }
# 
#     cudaFree(d_A);
#     cudaFree(d_B);
#     cudaFree(d_C);
# 
#     delete[] A;
#     delete[] B;
#     delete[] C;
# 
#     return 0;
# }

!nvcc matmul.cu -o matmul

!./matmul